name: 'Sync Shared Files'
description: 'Synchronize shared configuration files to team repositories'

inputs:
  target-repo:
    description: 'Target repository name'
    required: true
  source-dir:
    description: 'Source directory containing files to sync'
    required: true
  pat-token:
    description: 'Personal access token'
    required: true

runs:
  using: 'node20'
  pre: 'yarn install --frozen-lockfile'  # 의존성 설치 단계 추가
  main: 'index.js'
