name: Sync Dependencies

on:
  workflow_dispatch: # 수동 실행 트리거
  push:
    paths:
      - 'package.json'
      - 'yarn.lock'
    branches:
      - main

permissions:
  contents: write

jobs:
  sync-dependencies:
    strategy:
      matrix:
        repo: ['Left', 'Right']
      fail-fast: false # 하나가 실패해도 다른 것 계속 실행

    runs-on: ubuntu-latest
    steps:
      - name: Checkout child repository
        uses: actions/checkout@v4
        with:
          repository: KDT-PWA-Class-One-Group/KDT-PWA-1-Project-A-Team-${{ matrix.repo }}
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 1

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Download dependencies files
        run: |
          echo "Downloading files for ${{ matrix.repo }} repository..."

          # package.json 다운로드
          STATUS=$(curl -s -o package.json -w "%{http_code}" -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
            -L https://raw.githubusercontent.com/KDT-PWA-Class-One-Group/KDT-PWA-1-Project-A-Center/main/package.json)

          if [ $STATUS -ne 200 ]; then
            echo "Failed to download package.json (Status: $STATUS)"
            exit 1
          fi

      - name: Update Dependencies
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "Changes detected in ${{ matrix.repo }} repository"
            git add package.json
            git commit -m "chore: sync dependencies from center"
            git push || {
              echo "Push failed. Fetching latest changes and retrying..."
              git fetch
              git rebase origin/main
              git push
            }
          else
            echo "No changes to commit in ${{ matrix.repo }} repository"
          fi

      - name: Install dependencies
        if: success()
        run: yarn install
