name: Sync Dependencies

on:
  workflow_dispatch: # 수동 실행 트리거
  push:
    paths:
      - 'package.json'
      - 'yarn.lock'
    branches:
      - main

permissions:
  contents: write

jobs:
  sync-dependencies:
    strategy:
      matrix:
        repo: ['Left', 'Right']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout child repository
        uses: actions/checkout@v4
        with:
          repository: KDT-PWA-Class-One-Group/KDT-PWA-1-Project-A-Team-${{ matrix.repo }}
          token: ${{ secrets.PAT_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Download dependencies files
        run: |
          # package.json 다운로드
          curl -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
            -L https://raw.githubusercontent.com/KDT-PWA-Class-One-Group/KDT-PWA-1-Project-A-Center/main/package.json \
            -o package.json

          # yarn.lock 다운로드 (선택적)
          curl -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
            -L https://raw.githubusercontent.com/KDT-PWA-Class-One-Group/KDT-PWA-1-Project-A-Center/main/yarn.lock \
            -o yarn.lock

      - name: Update Dependencies
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "Changes detected in ${{ matrix.repo }} repository"
            git add package.json yarn.lock
            git commit -m "chore: sync dependencies from center"
            git push
          else
            echo "No changes to commit in ${{ matrix.repo }} repository"
          fi

      - name: Install dependencies
        if: success()
        run: yarn install
