name: Sync Dependencies

on:
  push:
    paths:
      - 'package.json'
      - 'yarn.lock'
    branches:
      - main

permissions:
  contents: write

jobs:
  sync-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update Left Repository
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          echo "Cloning Left repository..."
          git clone https://${{ secrets.PAT_TOKEN }}@github.com/KDT-PWA-Class-One-Group/KDT-PWA-1-Project-A-Team-Left.git temp-left

          echo "Copying package.json..."
          cp package.json temp-left/

          cd temp-left
          if [[ -n $(git status --porcelain) ]]; then
            git add package.json
            git commit -m "chore: sync dependencies from center"
            git push
          else
            echo "No changes to commit"
          fi
          cd ..

      - name: Update Right Repository
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          echo "Cloning Right repository..."
          git clone https://${{ secrets.PAT_TOKEN }}@github.com/KDT-PWA-Class-One-Group/KDT-PWA-1-Project-A-Team-Right.git temp-right

          echo "Copying package.json..."
          cp package.json temp-right/

          cd temp-right
          if [[ -n $(git status --porcelain) ]]; then
            git add package.json
            git commit -m "chore: sync dependencies from center"
            git push
          else
            echo "No changes to commit"
          fi
          cd ..
