name: Sync Dependencies

on:
  push:
    paths:
      - 'package.json'
      - 'yarn.lock'
    branches:
      - main

permissions:
  contents: write

jobs:
  sync-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update Left Repository
        run: |
          echo "Updating Left repository..."
          cp package.json ../KDT-PWA-1-Project-A-Team-Left

          cd ../KDT-PWA-1-Project-A-Team-Left
          if [[ -n $(git status --porcelain) ]]; then
            git config --local user.name "github-actions[bot]"
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git add package.json
            git commit -m "chore: sync dependencies from center"
            git push "https://${{ secrets.PAT_TOKEN }}@github.com/KDT-PWA-Class-One-Group/KDT-PWA-1-Project-A-Team-Left.git" main
          else
            echo "No changes to commit"
          fi
          cd ../KDT-PWA-1-Project-A-Team-Center

      - name: Update Right Repository
        run: |
          echo "Updating Right repository..."
          cp package.json ../KDT-PWA-1-Project-A-Team-Right

          cd ../KDT-PWA-1-Project-A-Team-Right
          if [[ -n $(git status --porcelain) ]]; then
            git add package.json
            git commit -m "chore: sync dependencies from center"
            git push "https://${{ secrets.PAT_TOKEN }}@github.com/KDT-PWA-Class-One-Group/KDT-PWA-1-Project-A-Team-Right.git" main
          else
            echo "No changes to commit"
          fi
          cd ../KDT-PWA-1-Project-A-Team-Center
