name: Sync Dependencies

on:
  push:
    paths:
      - 'package.json'
      - 'yarn.lock'
    branches:
      - main

permissions:
  contents: write

jobs:
  sync-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin "https://${{ secrets.PAT_TOKEN }}@github.com/KDT-PWA-Class-One-Group/KDT-PWA-1-Project-A-Center.git"

      - name: Sync Dependencies
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          # Center의 dependencies를 자식 저장소들에 복사
          node .github/scripts/sync-dependencies.js

          # 변경사항 커밋
          git add Project-A-Left/package.json Project-A-Right/package.json
          git commit -m "chore: sync dependencies from center" || echo "No changes to commit"

          # Left 저장소로 push
          LEFTREPO="https://${{ secrets.PAT_TOKEN }}@github.com/KDT-PWA-Class-One-Group/KDT-PWA-1-Project-A-Team-Left.git"
          git remote add left "$LEFTREPO"
          git subtree push --prefix Project-A-Left left main

          # Right 저장소로 push
          RIGHTREPO="https://${{ secrets.PAT_TOKEN }}@github.com/KDT-PWA-Class-One-Group/KDT-PWA-1-Project-A-Team-Right.git"
          git remote add right "$RIGHTREPO"
          git subtree push --prefix Project-A-Right right main
